# Generated by Django 5.1.15 on 2026-03-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_profile_interests"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="has_room",
            field=models.BooleanField(
                blank=True, help_text="Kya user ke paas kamra hai?", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("top", "Top"),
                    ("vers_top", "Vers Top"),
                    ("versatile", "Versatile"),
                    ("vers_bot", "Vers Bottom"),
                    ("bottom", "Bottom"),
                ],
                help_text="Top / Vers Top / Versatile / Vers Bottom / Bottom",
                max_length=10,
                null=True,
            ),
        ),
    ]
