# Generated by Django 5.1.15 on 2026-04-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_profile_has_room_profile_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="has_room",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("top", "Top"),
                    ("vers_top", "Vers Top"),
                    ("versatile", "Versatile"),
                    ("vers_bot", "Vers Bottom"),
                    ("bottom", "Bottom"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "otp"], name="api_emailot_email_9e1d37_idx"
                    )
                ],
            },
        ),
    ]
