# Generated by Django 4.2.7 on 2026-08-09 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_profile_has_room_alter_profile_position_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationUserState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cleared_at", models.DateTimeField(blank=True, null=True)),
                ("is_hidden", models.BooleanField(default=False)),
                ("hidden_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("week", "1 Week"),
                            ("month", "1 Month"),
                            ("three_months", "3 Months"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("razorpay_order_id", models.CharField(max_length=100, unique=True)),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "razorpay_signature",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=10,
                    ),
                ),
                ("is_trial", models.BooleanField(default=False)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="message",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages_deleted_for_everyone",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="deleted_for",
            field=models.ManyToManyField(
                blank=True, related_name="messages_hidden", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="is_deleted_for_everyone",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="is_live",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="latitude",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="longitude",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["-created_at"], name="api_convers_created_a39797_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["-created_at"], name="api_match_created_1eba9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "-created_at"],
                name="api_message_convers_404ef2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["is_live", "latitude", "longitude"],
                name="api_profile_is_live_3927f2_idx",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conversationuserstate",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_states",
                to="api.conversation",
            ),
        ),
        migrations.AddField(
            model_name="conversationuserstate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation_states",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["user", "-created_at"], name="api_subscri_user_id_49ad8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationuserstate",
            index=models.Index(
                fields=["user", "is_hidden"], name="api_convers_user_id_4d8983_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conversationuserstate",
            unique_together={("conversation", "user")},
        ),
    ]
