# Generated by Django 4.2.7 on 2026-10-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_notification_devicetoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="area_label",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
    ]
